---
title: "Lightening Round Essays"
format: html
editor: visual
author: "Christopher Hawkins"
eval: false
---

**Answer each of the following questions with *one sentence* including a brief explanation.**

1.  Finish the sentence with another student’s name: "If \[Name of Student\] doesn’t earn an A, then nobody should, because..." Explain your choice and your reasoning.

    Kyle Taschek. because during PA 4, 5, and 5.2 he was very knowledgeable and resourceful and together we were able to work really well to complete the assignments quickly and efficiently using each others skills.

2.  What was the most difficult part of the class for you? List a general topic, a specific problem, a kind of work we did, etc. and explain why.

    For me, the most difficult part was data wrangling. At first it was hard to understand the syntax and whether something modified a row or a column.

3.  What was the easiest part of the class for you? Explain why.

    For me, I really understood the writing function part of the class. I think it may come from the fact that I already knew how functions work and was able to easily adapt to the way function are written in R.

4.  What part of the class surprised or interested you the most? Explain why.

    I was surprise at how much I enjoyed making interesting visuals like figures and tables. I thought editing the format to exactly how I wanted was very satisfying.

5.  Give one piece of advice to a student just beginning a quarter of STAT 331 that will help them be successful in learning.

    I would recommend keeping the cards with the package information that were passed out during class and the practice activities. I thought they were really helpful as a reminder of what function exist and what they did instead of having to individually search them up.
